package edu.odu.cs.cs350;

public enum TokenName {

    OP_MULTIPLY, OP_DIVIDE, OP_MOD, OP_ADD, OP_SUBTRACT, OP_NEGATE,
    OP_LESS, OP_LESSEQUAL, OP_GREATER, OP_GREATEREQUAL, OP_EQUAL, OP_NOTEQUAL,
    OP_NOT, OP_ASSIGN, OP_AND, OP_OR,
    LEFTPAREN, RIGHTPAREN, LEFTBRACE, RIGHTBRACE, SEMICOLON, COMMA,
    KEYWORD_IF, KEYWORD_ELSE, KEYWORD_WHILE, KEYWORD_PRINT, KEYWORD_PUTC,
    IDENTIFIER, INTEGER, STRING,
    END_OF_INPUT, ERROR, POUND, LTBRACKET, RTBRACKET, SCOPE_OPERATER,
    PERIOD, QUESTION_MARK, DELETE_SYMBOL,OP_AT, EOF, WHILE, IF, BREAK, CASE, 
    CATCH, CHAR, CLASS, DEFAUlT, DELETE, DO, DOUBLE,ELSE, ENUM, EXPLICIT,
    CONTINUE,FALSE, FLOAT, FOR, GOTO, INLINE, INT, LONG, NAMESPACE, 
    NEW, NULLPTR, OPERATOR , PRIVATE, PROTECTED, PUBLIC,
    REGISTER, REQUIRES, RETURN, SHORT, SIGNED, SIZEOF, STATC, STACTIC_CAST,
    STRUCT, SWITCH, TEMPLATE, THIS, THROW, TRUE, TRY, TYPEDEF, TYPENAME,
    UNION, UNSIGNED, USING, VIRTUAL, VOID, IOSTREAM, STD, 
    EQ, GT, LT, NOT, COMP, QUESTION, COLON, EQEQ, LTEQ, NOTEQ,
    ANDAND, OROR, PLUSPLUS, MINUSMINUS, PLUS, MINUS, MULT, DIV,
    AND, OR, XOR, MOD, LSHIFT, RSHIFT, URSHIFT,PLUSEQ, MINUSEQ, MULTEQ,
    DIVEEQ,ANDEQ, OREQ,MODEQ ,LSHIFTEQ, RSHIFTEQ, UPSHIFTEQ, BOOL, CONSTANT_NUMBERS,
    LPAREN, RPAREN, LBRACE, RBRACE, RBRACK, LBRACK, DOT, KEYWORD, BOOLEAN_LITERAL,
    NULL_LITERAL
    
}
