name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest    
    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      run: ./gradlew build
    - name: Set up local gh-pages branch 
      run: |
         git checkout -b gh-pages origin/gh-pages  # make sure that gh-pages branch is available
         git checkout main # but then go back to main
- name: updateGHPages task
      run: ./gradlew updateGHPages
